import React, { useEffect } from "react";
import { Link } from "react-scroll";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div id="top">
      <div className="relative pt-[100px] pb-[56px] lg:pb-[60px] lg:pt-[130px]">
        <div className="font-bold text-[30px] text-center">
          Privacy and Policy
        </div>
        <div>
          This privacy policy describes the policies and procedures which guides
          how ParkinSpace collects, uses and discloses your information when you
          use the service and tells you about your privacy rights and how the
          law protects You.
        </div>
        <div className="my-[10px]">
          We may change this privacy policy from time to time. If we make
          changes, we will notify you by revising the date at the top of this
          policy, and in some cases, we may provide you with additional notice
          (such as by adding a statement to the homepages of our website or
          [mobile application] or by sending you an email notification).
        </div>
        <div>
          We encourage you to review the Privacy Policy whenever you interact
          with us to stay informed about our information practices and the ways
          you can help protect your privacy.
        </div>
        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Interpretation and Definitions
        </div>

        <div className="font-medium mb-[5px]">Interpretation </div>
        <div>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </div>
        <div className="font-medium my-[5px]">Definitions</div>
        <div>For the purposes of this privacy policy: </div>
        <div className="mt-[5px]">
          <span className="font-medium mb-[5px]"> Account</span> means a unique
          account created for you to access our service or parts of our service.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Company</span> (referred to
          as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers
          to ParkinSpace
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Cookies</span> are small
          files that are placed on your computer, mobile device or any other
          device by a website, containing the details of your browsing history
          on that website among its many uses.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Country</span> refers to
          Nigeria
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Device</span> means any
          device that can access the service such as a computer, a cellphone or
          a digital tablet.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Personal Data </span> is any
          information that relates to an identified or identifiable individual.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Service</span> refers to the
          Website.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Service Provider</span> means
          any natural or legal person who processes the data on behalf of the
          Company. It refers to third-party companies or individuals employed by
          the Company to facilitate the service, to provide the service on
          behalf of the Company, to perform services related to the service or
          to assist the Company in analyzing how the service is used.
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Usage Data</span> refers to
          data collected automatically, either generated by the use of the
          service or from the service infrastructure itself (for example, the
          duration of a page visit).
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> Website </span> refers to
          Parkinspace, accessible via{" "}
          <a
            href="https://parkinspace.ng"
            target="_blank"
            className="text-[blue]"
          >
            parkinspace.ng
          </a>
        </div>
        <div>
          <span className="font-medium  mb-[5px]"> You </span> means the
          individual accessing or using the service, or the company, or other
          legal entity on behalf of which such individual is accessing or using
          the service, as applicable.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Collecting and Using your Personal Data
        </div>
        <div>
          While using our service, we may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </div>

        <li>Email address </li>
        <li>First name and last name </li>
        <li>Phone number </li>
        <li>Address, City, State </li>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Usage Data
        </div>
        <div>
          Usage Data is collected automatically when using the service. Usage
          Data may include information such as your Device’s Internet Protocol
          address (e.g. IP address), browser type, browser version, the pages of
          our service that You visit, the time and date of your visit, the time
          spent on those pages, unique device identifiers and other diagnostic
          data.
        </div>
        <div className="my-[10px]">
          When you access the service by or through a mobile device, we may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, your mobile device unique ID,
          the IP address of your mobile device, your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </div>
        <div>
          We may also collect information that your browser sends whenever You
          visit our service or when You access the service by or through a
          mobile device.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Legal Basis for processing of personal information
        </div>
        <div className="mb-[10px]">
          We will only process your personal information where we have a legal
          basis to do so. The legal basis will depend on the purpose for which
          we have collected and use your personal information. The legal basis
          for processing is any of the following:
        </div>
        <li>
          Consent: This will apply where you have provided your consent to the
          processing of your personal data for one or more specific purposes;
        </li>
        <li>
          Performance of a contract with you: This will apply where processing
          is necessary for the performance of a contract to which you are a
          party or in order to take steps prior to entering into a contract with
          you;
        </li>
        <li>
          Protection of vital interests:This is where processing is required for
          the protection of your vital interests.
        </li>
        <li>
          Compliance with law: Where we are subject to a legal obligation and
          need to use your personal information in order to comply with that
        </li>
        <li>
          Public interest: Where processing is necessary for the performance of
          a task or function carried out in the interest of the public.
        </li>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Use of your Personal Data
        </div>
        <div className="mb-[10px]">
          The Company may use Personal Data for the following purposes:
        </div>
        <li>
          To provide and maintain our service, including to monitor the usage of
          our service.
        </li>
        <li>
          To manage your Account: to manage your registration as a user of the
          service. The Personal Data You provide can give You access to
          different functionalities of the service that are available to You as
          a registered user.
        </li>
        <li>
          To contact You: To contact You by email, telephone calls, SMS, or
          other equivalent forms of electronic communication, such as a mobile
          application’s push notifications regarding updates or informative
          communications related to the functionalities, products or contracted
          services, including the security updates, when necessary or reasonable
          for their implementation.
        </li>
        <li>
          To provide You with news, special offers and general information about
          other goods, services and events which we offer that are similar to
          those that you have already purchased or enquired about unless You
          have opted not to receive such information.
        </li>
        <li>
          To manage your requests: To attend and manage your requests to Us.
        </li>
        <li>
          For other purposes: We may use your information for other purposes,
          such as data analysis, identifying usage trends, determining the
          effectiveness of our promotional campaigns and to evaluate and improve
          our service, products, services, marketing and your experience.
        </li>
        <div className="my-[10px]">
          We may share your personal information in the following situations:
        </div>
        <li>
          With service Providers: We may share your personal information with
          service Providers to monitor and analyze the use of our service, to
          contact You.
        </li>
        <li>
          For business transfers: We may share or transfer your personal
          information in connection with, or during negotiations of, any merger,
          sale of Company assets, financing, or acquisition of all or a portion
          of Our business to another company.
        </li>
        <li>
          With Affiliates: We may share your information with Our affiliates, in
          which case we will require those affiliates to honor this Privacy
          Policy. Affiliates include Our parent company EZPark and any other
          subsidiaries, joint venture partners or other companies that We
          control or that are under common control with Us.
        </li>
        <li>
          With business partners: We may share your information with Our
          business partners to offer You certain products, services or
          promotions.
        </li>
        <li>
          With other users: when You share personal information or otherwise
          interact in the public areas with other users, such information may be
          viewed by all users and may be publicly distributed outside.
        </li>
        <li>
          With your consent: We may disclose your personal information for any
          other purpose with your consent.
        </li>
        <div className="my-[10px]">
          We may share your data without your consent in any of the following
          situations:
        </div>
        <li>
          If we are under a duty to disclose or share your personal data in
          order to comply with any legal obligation, or in order to enforce or
          apply our terms of use and other agreements; or to protect the rights,
          property, or safety of EZPark Limited, our clients, or others;
        </li>
        <li>
          Where we are requested to provide information by authorized third
          parties or regulatory/governmental agencies investigating illegal
          activities;
        </li>
        <li>
          In the event that we sell or buy any business or assets, in which case
          we will disclose your personal data to the prospective seller or buyer
          of such business or assets;
        </li>
        <li>
          If EZPark Limited or substantially all of its assets are acquired by a
          third party, in which case personal data held by it about its clients
          will be one of the transferred assets;
        </li>
        <li>
          We may hold events including seminars and conferences which are
          sponsored by third parties or have third party speakers. Where you
          register for one of these events, we may share your details with those
          third parties;
        </li>
        <div className="my-[10px] font-medium">Where we Store your Data </div>
        <div>
          The data that we collect from you will be transferred to and stored at
          destinations within and outside Nigeria. By submitting your personal
          data, you agree to this transfer, storing or processing. We will take
          all steps reasonably necessary to ensure that your data is treated
          securely and in accordance with this privacy policy.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Retention of your Personal Data
        </div>
        <div>
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </div>
        <div className="mt-[10px]">
          The Company will also retain Usage Data for internal analysis
          purposes. Usage Data is generally retained for a shorter period of
          time, except when this data is used to strengthen the security or to
          improve the functionality of Our service, or We are legally obligated
          to retain this data for longer time periods.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Transfer of your Personal Data
        </div>
        <div>
          Your information, including Personal Data, is processed at the
          Company’s operating offices and in any other places where the parties
          involved in the processing are located. It means that this information
          may be transferred to — and maintained on — computers located outside
          of your state, province, country or other governmental jurisdiction
          where the data protection laws may differ than those from your
          jurisdiction.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Privacy by Design
        </div>
        <div>
          When designing and implementing a new business feature or
          technological process involving the collection or use of personal
          data, we will take into consideration, among its other consideration,
          the need for structured privacy planning for this process. For
          example, the company will consider collecting only the type of
          information required for the business process in the first place.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Security
        </div>
        <div>
          We adopt robust technologies and policies to ensure the personal
          information we hold about you is suitably protected. We take steps to
          protect your information from unauthorized access and against unlawful
          processing, accidental loss, destruction and damage. Where you have
          chosen a password that allows you to access certain parts of the
          website and mobile application, you are responsible for keeping this
          password confidential. We advise you not to share your password with
          anyone. We have also taken measures to comply with global Information
          Security Management Systems (ISMS) we therefore have put in place
          digital and physical security measures to limit or eliminate
          possibilities of data privacy breach incidents.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Disclosure of your Information
        </div>
        <div className="mb-[10px]">
          We will usually not share your personal information with other third
          parties without your consent. Where we need to transfer your data to
          another country, such country must have an adequate data protection
          law. We will seek your consent where we need to send your data to a
          country without an adequate data protection law. You agree that we
          have the right to share your personal information with:
        </div>
        <li>
          any member of our group, which means our subsidiaries, our ultimate
          holding company and its subsidiaries, as defined under the Companies
          and Allied Matters Act 2020.
        </li>
        <li>
          authorized employees of EZPark Limited only for the purpose of
          resolving issues associated with the use of our products.
        </li>
        <div className="mt-[10px]">
          Selected third parties including: business partners, suppliers or
          sub-contractors for the performance of any contract we enter into with
          them; advertisers and advertising networks that require the data to
          select and serve relevant adverts to you and others. We do not
          disclose information about identifiable individuals to our
          advertisers, but we will provide them with aggregate information about
          our users. We may also use such aggregate information to help
          advertisers reach the kind of audience they want to target; analytics
          and search engine providers that assist us in the improvement and
          optimisation of our corporate and products website.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Your Rights
        </div>
        <div className="mb-[10px]">
          The law gives you certain rights in respect of the information we hold
          about you. Below is a highlight of some of those rights. It is not a
          complete, exhaustive statement of your rights in respect of your
          personal data.
        </div>
        <li>
          You have a right to consent to this Privacy Policy and to withdraw
          your consent at any time. You have a right to a copy of the personal
          data we hold about you, as well as the information about what we do
          with it, who we share it with and how long we hold it for. We may make
          a reasonable charge for additional copies of that data in the case of
          unfounded and excessive requests.You have a right to freely transfer
          your data received from us to any other
        </li>
        <li>
          You have the right to have the information we hold about you
          corrected, if it is factually inaccurate. You may contact us for this
          purpose.
        </li>
        <li>
          In some circumstances, you have the right to the deletion of the
          information that we hold about you. You have a right to lodge a
          complaint about the handling of your personal information with the
          National Information Technology Development Agency (NITDA).
        </li>
        <li>
          You have the right to ask us not to process your personal data for
          marketing purposes. We will usually inform you (before collecting your
          data) if we intend to use your data for such purposes or if we intend
          to disclose your information to any third party for such purposes.
        </li>
        <div className="mt-[10px]">
          NITDA's website (NITDA Act -
          <a
            className="text-[blue]"
            href="https://nitda.gov.ng/nit/)"
            target="_blank"
            //
          >
            NITDA
          </a>{" "}
          has a wealth of useful information in respect of your rights over your
          personal data.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Changes to our Privacy Policy
        </div>
        <div>
          Any changes we make to this Policy in the future will be posted on
          this page and, where appropriate, notified to you by e-mail. Please
          check back frequently to see any updates or changes to this Policy.
        </div>
        <div className="my-[10px] font-medium">Breach/Privacy Violation </div>
        <div>
          In the event of a breach of security leading to the accidental or
          unlawful destruction, loss, alteration, unauthorized disclosure of, or
          access to Personal Data, we shall within 72 (Seventy-Two) hours of
          having knowledge of such breach report the details of the breach to
          NITDA.
        </div>
        <div>
          Furthermore, where we ascertain that such breach is detrimental to
          your rights and freedoms in relation to your Personal Data, we shall
          within 7 (Seven) days of having knowledge of the occurrence of such
          breach take steps to inform you of the breach incident, the risk to
          your rights and freedoms resulting from such breach and any course of
          action to remedy said breach.
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Contact
        </div>
        <div>
          Questions, comments and requests regarding this Privacy Policy should
          be addressed to{" "}
          <a
            href="https://parkinspace.ng/contact-us"
            target="_blank"
            className="text-[blue]"
          >
            https://parkinspace.ng/contact-us
          </a>
        </div>

        <div className="font-medium text-[20px] mt-[20px] mb-[10px]">
          Consent
        </div>
        <div>
          You accept this Privacy Policy and hereby give the Company consent to
          save, process and use your Personal Data to the extent as allowed by
          law when you provide us with details of your Personal Data or by
          clicking on the “accept” button. Note that you can withdraw your
          consent at any time, however such withdrawal of consent would not
          affect the lawfulness of processing information based on consent given
          before its withdrawal.
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
